name: feature-branch
on:
  push:
    branches: [ 'feature/locust/**' ]
jobs:
  update-feature-branch-list:
    runs-on: ubuntu-latest
    steps:
      - name: 01. Checkout repository 
        uses: actions/checkout@v4
      
      - name: 02. Set the current branch and the microservice name 
        run: |
          # The rule of feature branch for this workflow.
          # -> feature/{MICROSERVICE}/{WHATEVERYOUWANT}
          # -> The '/' needs to be used only above case.
          # An example of GITHUB_REF : refs/heads/feature/kafkaconnect-eventlake/test-hello-test
          # An example of ${GITHUB_REF#*heads/} : feature/kafkaconnect-eventlake/test-hello-test
          # An example of ${GITHUB_REF#*heads/feature} : kafkaconnect-eventlake/test-hello-test

          CURRENT_BRANCH=`echo ${GITHUB_REF#*heads/}`
          SERVICE_NAME=`echo ${CURRENT_BRANCH} | awk -F'/' '{print $2}'`
          UNIQUE_NAME=`echo ${currentBranch} | awk -F'/' '{print $3}' | tr -d '[:punct:]' | cut -c 1-10 | tr -d '[:space:]';echo''`
          FILE_NAME=`echo ${GITHUB_REF#*heads/feature} | tr '/' '-'`
          echo "CURRENT_BRANCH=${CURRENT_BRANCH}" >> $GITHUB_ENV
          echo "SERVICE_NAME=${SERVICE_NAME}" >> $GITHUB_ENV
          echo "UNIQUE_NAME=${UNIQUE_NAME}" >> $GITHUB_ENV
          echo "FILE_NAME=${FILE_NAME}" >> $GITHUB_ENV

      - name: 03. Checkoutbranch feature-branch-list
        uses: actions/checkout@v4
        with:
          ref: feature-branch-list

      - name: 04. Update feature branch config file
        shell: bash 
        run: |
          apt-get install -y jq
          echo `{"branchName": "${{ env.CURRENT_BRANCH }}", "serviceName": "${{ env.SERVICE_NAME }}", "uniqueName": "${{ env.UNIQUE_NAME }}"}` > ./feature-branch-list/${{ env.FILE_NAME }}.json
          # branchList=""
          # for file in ./feature-branch-list/*;
          # do
          #   branchList=$
          cat ./feature-branch-list/${{ env.FILE_NAME }}.json

      - name: 05. Commit and Push files
        uses: EndBug/add-and-commit@v9
        with:
          add: ./feature-branch-list/${{ env.FILE_NAME }}.json
          message: 'GIT-ACTIONS: Updated "${{ env.FILE_NAME }}" JSON File on feature-branch-list'
          commiter_name: Github Actions
          commiter_email: actions@github.com
          commit: --signoff
          push: true